### ISSUE TITLE
Kanban board review

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/cubis#12]
- [ ]  2 students in the group (student A → Hammed Adisa, Student B → Baroka Irotori)
- [ ] Add the to-do list in the project
- [ ] Assignees all task to students
- [ ] Project link : https://github.com/Baroka-wp/cubis/projects/1

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi team, 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good luck with the project 🤞🏻 

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
